#!/bin/bash

if [ $# -ne 2 ]; then

RED='\033[1;31m'
NC='\033[0m'
printf "${RED}2 arguments are expected : {save_path, fps}\n${NC}"

else

export PYTHONPATH=${PYTHONPATH}:/home/dhm/icu-suite/repositories/pose-estimation
python3 /home/dhm/icu-suite/repositories/pose-estimation/datacollection/run_rs_op_origin_3cam.py \
        --save-path=${1}-${2}\
        --fps=${2}

echo "FINISHED"

fi
